### ISSUE TITLE
How to use hack box

Whats uses of Hack box guide and help me.

### ISSUE THREAD

**Issue by Tikku31892** [strellic/Hackbox#1]

**Comment by strellic** [comment]
If you've seen websites like [TryHackMe](https://tryhackme.com/) or [HackTheBox](https://www.hackthebox.eu/), this is meant to be an open-source clone of their website. Those websites have "rooms", which have vulnerable "boxes" that people can launch and try to hack into. Hackbox does the same thing, so you can clone this repo and create vulnerable Docker images, and then add them to the website.
